// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// step1_counter //
// ------------- //

#define step1_counter_wrap_target 0
#define step1_counter_wrap 9
#define step1_counter_pio_version 0

static const uint16_t step1_counter_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xc005, //  2: irq    nowait 5
    0x00c7, //  3: jmp    pin, 7
    0x1927, //  4: jmp    !x, 7           side 1 [1]
    0xd024, //  5: irq    wait 4          side 0
    0x0042, //  6: jmp    x--, 2
    0xa0c1, //  7: mov    isr, x
    0x8000, //  8: push   noblock
    0xc000, //  9: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program step1_counter_program = {
    .instructions = step1_counter_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = step1_counter_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config step1_counter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + step1_counter_wrap_target, offset + step1_counter_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ----------- //
// step1_speed //
// ----------- //

#define step1_speed_wrap_target 0
#define step1_speed_wrap 4
#define step1_speed_pio_version 0

static const uint16_t step1_speed_program_instructions[] = {
            //     .wrap_target
    0x20c5, //  0: wait   1 irq, 5
    0xe045, //  1: set    y, 5
    0xa942, //  2: nop                           [9]
    0x0082, //  3: jmp    y--, 2
    0xc044, //  4: irq    clear 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program step1_speed_program = {
    .instructions = step1_speed_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = step1_speed_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config step1_speed_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + step1_speed_wrap_target, offset + step1_speed_wrap);
    return c;
}
#endif

// ------------- //
// step2_counter //
// ------------- //

#define step2_counter_wrap_target 0
#define step2_counter_wrap 9
#define step2_counter_pio_version 0

static const uint16_t step2_counter_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xc007, //  2: irq    nowait 7
    0x00c7, //  3: jmp    pin, 7
    0x1927, //  4: jmp    !x, 7           side 1 [1]
    0xd026, //  5: irq    wait 6          side 0
    0x0042, //  6: jmp    x--, 2
    0xa0c1, //  7: mov    isr, x
    0x8000, //  8: push   noblock
    0xc001, //  9: irq    nowait 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program step2_counter_program = {
    .instructions = step2_counter_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = step2_counter_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config step2_counter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + step2_counter_wrap_target, offset + step2_counter_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ----------- //
// step2_speed //
// ----------- //

#define step2_speed_wrap_target 0
#define step2_speed_wrap 4
#define step2_speed_pio_version 0

static const uint16_t step2_speed_program_instructions[] = {
            //     .wrap_target
    0x20c7, //  0: wait   1 irq, 7
    0xe045, //  1: set    y, 5
    0xa942, //  2: nop                           [9]
    0x0082, //  3: jmp    y--, 2
    0xc046, //  4: irq    clear 6
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program step2_speed_program = {
    .instructions = step2_speed_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = step2_speed_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config step2_speed_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + step2_speed_wrap_target, offset + step2_speed_wrap);
    return c;
}

#include "hardware/clocks.h"
void step1_counter_program_init(PIO pio, uint sm, uint offset, uint step_pin, uint hold_pin,float freq) {
    pio_sm_config c = step1_counter_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, step_pin);
    sm_config_set_set_pins(&c, step_pin, 1);
    sm_config_set_jmp_pin(&c, hold_pin);
    pio_gpio_init(pio, step_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, step_pin, 1, true);
    float div = clock_get_hz(clk_sys) / (freq);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
void step1_speed_program_init(PIO pio, uint sm, uint offset, float freq) {
    pio_sm_config c = step1_speed_program_get_default_config(offset);
    float div = clock_get_hz(clk_sys) / (freq);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
void step2_counter_program_init(PIO pio, uint sm, uint offset, uint step_pin, uint hold_pin, float freq) {
    pio_sm_config c = step2_counter_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, step_pin);
    sm_config_set_set_pins(&c, step_pin, 1);
    sm_config_set_jmp_pin(&c, hold_pin);
    pio_gpio_init(pio, step_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, step_pin, 1, true);
    float div = clock_get_hz(clk_sys) / (freq);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
void step2_speed_program_init(PIO pio, uint sm, uint offset, float freq) {
    pio_sm_config c = step2_speed_program_get_default_config(offset);
    float div = clock_get_hz(clk_sys) / (freq);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

